services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    container_name: librereserva-postgres
    environment:
      POSTGRES_DB: reservas
      POSTGRES_USER: curso
      POSTGRES_PASSWORD: solo-laboratorio
    ports:
      - "5432:5432"
    volumes:
      - reservas_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U curso -d reservas"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: docker.io/library/rabbitmq:4-management-alpine
    container_name: librereserva-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: curso
      RABBITMQ_DEFAULT_PASS: solo-laboratorio
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - reservas_rabbit:/var/lib/rabbitmq

volumes:
  reservas_pg:
  reservas_rabbit:
